## NOTE: For multi-platform builds in OrbStack, you'll need to enable"containerd image store",
## by adding the following settings to "OrbStack Settings > Docker"
## (see https://github.com/orbstack/orbstack/issues/887#issuecomment-2388088120)
#
# {
#   "features" : {
#     "containerd-snapshotter" : true
#   }
# }
#
services:
  web:
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: phoenix-lunch-and-learn
    image: ghcr.io/rickclare/phoenix-lunch-and-learn:1.2
    ports:
      - "4000:4000"
      - "4443:4443"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/deps
      - /app/_build
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app
    #       ignore:
    #         - _build/
    #         - deps/
    #         - node_modules/
    #     - action: rebuild
    #       path: package.json
    #     - action: rebuild
    #       path: mix.lock
