import Config

logger_level = "LOGGER_LEVEL" |> System.get_env("debug") |> String.to_existing_atom()

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"
config :logger, level: logger_level

# Configure your database
config :lunch, Lunch.Repo, database: "priv/db/development.db"

config :lunch, LunchWeb.Endpoint,
  # For development, we disable any cache and enable
  # debugging and code reloading.
  #
  # The watchers configuration can be used to run external
  # watchers to your application. For example, we can use it
  # to bundle .js and .css sources.
  # Binding to loopback ipv4 address prevents access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  url: [scheme: "https", host: "localhost"],
  https: [
    port: 4443,
    cipher_suite: :strong,
    certfile: "priv/cert/selfsigned.pem",
    keyfile: "priv/cert/selfsigned_key.pem"
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "6FImzEYx73q3bKQbLvNFaO/8pmu1SaVoKOygnYhHveq0mHKREWp/Z6waPCvDcW8R",
  watchers: [
    bun: {Bun, :install_and_run, [:js, ~w(--sourcemap=external --watch)]},
    bun: {Bun, :install_and_run, [:css, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
config :lunch, LunchWeb.Endpoint,
  live_reload: [
    patterns: [
      # ## SSL Support
      #
      # In order to use HTTPS in development, a self-signed
      # certificate can be generated by running the following
      # Mix task:
      #
      #     mix phx.gen.cert
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/lunch_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
config :lunch, dev_routes: true

# Initialize plugs at runtime for faster development compilation
#
#     https: [
#       port: 4001,
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
#       cipher_suite: :strong,
# in production as building large stacktraces may be expensive.
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  #
  # If desired, both `http:` and `https:` keys can be
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  # configured to run both http and https servers on
  # different ports.

  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
